export const colorStyleProps: Record<string, true> = {
  borderColor: true,
  borderLeftColor: true,
  borderRightColor: true,
  borderTopColor: true,
  borderBottomColor: true,
  borderBlockColor: true,
  borderStartColor: true,
  borderEndColor: true,
  borderBlockEndColor: true,
  borderBlockStartColor: true,
  backgroundColor: true,
  background: true,
  color: true,
  textDecorationColor: true,
  textShadowColor: true,
  shadowColor: true,
  tintColor: true,
  overlayColor: true,
  cursorColor: true,
};

export const dimensionStyleProps: Record<string, true> = {
  flex: true,
  flexBasis: true,
  flexGrow: true,
  flexShrink: true,
  rowGap: true,
  columnGap: true,
  gap: true,
  borderWidth: true,
  borderBottomWidth: true,
  borderLeftWidth: true,
  borderRightWidth: true,
  borderTopWidth: true,
  borderRadius: true,
  borderBottomLeftRadius: true,
  borderBottomRightRadius: true,
  borderTopLeftRadius: true,
  borderTopRightRadius: true,
  borderEndWidth: true,
  borderStartWidth: true,
  borderBottomEndRadius: true,
  borderBottomStartRadius: true,
  borderTopEndRadius: true,
  borderTopStartRadius: true,
  borderEndEndRadius: true,
  borderEndStartRadius: true,
  borderStartEndRadius: true,
  borderStartStartRadius: true,
  bottom: true,
  left: true,
  right: true,
  top: true,
  zIndex: true,
  height: true,
  minHeight: true,
  maxHeight: true,
  width: true,
  minWidth: true,
  maxWidth: true,
  aspectRatio: true,
  margin: true,
  marginBottom: true,
  marginLeft: true,
  marginRight: true,
  marginTop: true,
  marginHorizontal: true,
  marginVertical: true,
  marginEnd: true,
  marginStart: true,
  padding: true,
  paddingBottom: true,
  paddingLeft: true,
  paddingRight: true,
  paddingTop: true,
  paddingHorizontal: true,
  paddingVertical: true,
  paddingEnd: true,
  paddingStart: true,
  fontSize: true,
  lineHeight: true,
  letterSpacing: true,
  elevation: true,
  textShadowRadius: true,
  shadowRadius: true,
  shadowOffset: true,
  inset: true,
  insetBlock: true,
  insetInline: true,
  scrollX: true,
  scrollY: true,
  textIndent: true,
};

export const otherStyleProps: Record<string, true> = {
  alignContent: true,
  alignItems: true,
  alignSelf: true,
  flexDirection: true,
  flexWrap: true,
  justifyContent: true,
  borderStyle: true,
  position: true,
  display: true,
  overflow: true,
  transform: true,
  transformOrigin: true,
  backfaceVisibility: true,
  opacity: true,
  fontFamily: true,
  fontStyle: true,
  fontWeight: true,
  fontVariant: true,
  textAlign: true,
  textDecorationLine: true,
  textDecorationStyle: true,
  textTransform: true,
  userSelect: true,
  direction: true,
  end: true,
  start: true,
  textAlignVertical: true,
  shadowOpacity: true,
  resizeMode: true,
  writingDirection: true,
  includeFontPadding: true,
  pointerEvents: true,
  verticalAlign: true,
  objectFit: true,
  objectPosition: true,
  accessible: true,
  scrollEnabled: true,
  fadingEdgeLength: true,
  transition: true,
};

export const allStyleProps: Record<string, true> = {
  ...colorStyleProps,
  ...dimensionStyleProps,
  ...otherStyleProps,
};
