import { ThemeConfig } from '@symbiot-core-apps/theme';

export const lightTheme: ThemeConfig = {
  background: '#F2F2F2',
  background1: '#FFFFFF',
  color: '#000000',
  colorPress: '#000000',
  error: '#C62828',
  link: '#777777',
  placeholderColor: '#999999',
  disabled: '#999999',
  borderColor: '#111111',
  borderColorHover: 'transparent',
  borderColorFocus: 'transparent',
  outlineColor: 'transparent',
  buttonBackground: '#7b5aed',
  buttonTextColor: '#FFFFFF',
  buttonTextColor1: '#7b5aed',
  checkboxColor: '#7b5aed',
  inputBackgroundColor: '#FFFFFF',
};

export const darkTheme: ThemeConfig = {
  background: '#000000',
  background1: '#1A1A1A',
  color: '#FFFFFF',
  colorPress: '#FFFFFF',
  error: '#FF6B6B',
  link: '#777777',
  placeholderColor: '#999999',
  disabled: '#999999',
  borderColor: '#F5F5F5',
  borderColorHover: 'transparent',
  borderColorFocus: 'transparent',
  outlineColor: 'transparent',
  buttonBackground: '#7b5aed',
  buttonTextColor: '#FFFFFF',
  buttonTextColor1: '#7b5aed',
  checkboxColor: '#7b5aed',
  inputBackgroundColor: '#1A1A1A',
};
