import { ReactElement } from 'react';
import { IconProps } from './icon-props';

export type IconName =
  | 'AddCircle'
  | 'AddSquare'
  | 'AltArrowDown'
  | 'AltArrowLeft'
  | 'AltArrowRight'
  | 'AltArrowUp'
  | 'ArrowLeft'
  | 'ArrowRight'
  | 'Bell'
  | 'Calendar'
  | 'CalendarMinimalistic'
  | 'Camera'
  | 'CloseCircle'
  | 'Code'
  | 'CodeCircle'
  | 'CrownLine'
  | 'FileText'
  | 'Gallery'
  | 'Global'
  | 'Heart'
  | 'Home'
  | 'HomeAdd'
  | 'Login'
  | 'Letter'
  | 'Logout2'
  | 'MagicStick'
  | 'Maximize'
  | 'MenuDotsCircle'
  | 'Minimize'
  | 'Moon'
  | 'PaperclipRounded'
  | 'Pen'
  | 'QrCode'
  | 'QuestionCircle'
  | 'Rocket'
  | 'SettingsMinimalistic'
  | 'Share'
  | 'ShareCircle'
  | 'Suitcase'
  | 'Sun'
  | 'TrashBinMinimalistic'
  | 'TuningSquare'
  | 'Unread'
  | 'UserCircle'
  | 'Widget'
  | 'Widget3';
export type IconMap = Record<IconName, (props: IconProps) => ReactElement>;
