import { AppSettings } from '@symbiot-core-apps/api';

const languages = {
  uk: require('./i18n/uk.json'),
  en: require('./i18n/en.json'),
};

export const appSettings: AppSettings = {
  language: {
    default: 'en',
    translations: languages,
  },
  functionality: {
    canLeaveReview: true,
    limits: {
      default: {
        clients: 100,
        services: 10,
        employees: 0,
        locations: 0,
        periodMemberships: 10,
        visitMemberships: 10,
      },
    },
    availability: {
      brandCompetitor: true,
      brandIndustry: true,
      servicePrice: true,
    },
  },
  icons: {
    Home: 'Home',
    Notifications: 'Bell',
    Calendar: 'Calendar',
    TabsPlus: 'AddSquare',
    Workspace: 'Suitcase',
    Service: 'Plate',
    Package: 'Library',
    More: 'Widget',
    PeriodBasedMembership: 'Card2',
    VisitBasedMembership: 'Ticket',
    UnavailableBooking: 'CalendarCross',
    ServiceBooking: 'Calendar',
  },
  theme: {
    light: {
      background: '#F2F2F2',
      background1: '#FFFFFF',
      background2: '#FFFFFF50',
      overlay: '#11111180',
      color: '#000000',
      colorPress: '#000000',
      error: '#C62828',
      link: '#7B5AED',
      placeholderColor: '#999999',
      disabled: '#999999',
      highlighted: '#EEEEEE',
      borderColor: '#111111',
      borderColorHover: 'transparent',
      borderColorFocus: 'transparent',
      outlineColor: 'transparent',
      buttonBackground: '#7B5AED',
      buttonTextColor: '#FFFFFF',
      buttonTextColor1: '#7B5AED',
      checkboxColor: '#7B5AED',
      inputBackgroundColor: '#FFFFFF',
      tabBarActiveTintColor: '#7B5AED',
      tabBarInactiveTintColor: '#999999',
      qrCode: '#191919',
      qrCodeGradientFrom: '#7B5AED',
      qrCodeGradientTo: '#7B5AED60',
      switchSelectedColor: '#7B5AED',
      calendarHeaderBackgroundColor: '#FAFAFA',
      calendarBackgroundColor: '#FFFFFF',
      calendarLineColor: '#EFEFEF',
      calendarTimeColor: '#191919',
      calendarTodayColor: '#7B5AED',
      calendarNowIndicatorColor: '#7B5AED',
      calendarUnavailableSlotBackgroundColor: '#EEEEEE',
      calendarUnavailableSlotColor: '#777777',
      calendarUnavailableSlotMarkerColor: '#DDDDDD',
      calendarServiceSlotBackgroundColor: '#8790FF30',
      calendarServiceSlotColor: '#000000',
      calendarServiceSlotMarkerColor: '#8790FF',
      subscriptionBorderColor: '#FEFEFE',
      subscriptionBackgroundColor: '#F2F2F2',
      selectedSubscriptionBorderColor: '#8790FF',
      selectedSubscriptionBackgroundColor: '#8790FF30',
    },
    dark: {
      background: '#000000',
      background1: '#191919',
      background2: '#19191950',
      overlay: '#11111180',
      color: '#FFFFFF',
      colorPress: '#FFFFFF',
      error: '#FF6B6B',
      link: '#7B5AED',
      placeholderColor: '#999999',
      disabled: '#999999',
      highlighted: '#333333',
      borderColor: '#F5F5F5',
      borderColorHover: 'transparent',
      borderColorFocus: 'transparent',
      outlineColor: 'transparent',
      buttonBackground: '#7B5AED',
      buttonTextColor: '#FFFFFF',
      buttonTextColor1: '#7B5AED',
      checkboxColor: '#7B5AED',
      inputBackgroundColor: '#1A1A1A',
      tabBarActiveTintColor: '#7B5AED',
      tabBarInactiveTintColor: '#999999',
      qrCode: '#F5F5F5',
      qrCodeGradientFrom: '#7B5AED',
      qrCodeGradientTo: '#7B5AED20',
      switchSelectedColor: '#7B5AED',
      calendarHeaderBackgroundColor: '#0F0F0F',
      calendarBackgroundColor: '#000000',
      calendarLineColor: '#1A1A1A',
      calendarTimeColor: '#DDDDDD',
      calendarTodayColor: '#7B5AED',
      calendarNowIndicatorColor: '#7B5AED',
      calendarUnavailableSlotBackgroundColor: '#333333',
      calendarUnavailableSlotColor: '#777777',
      calendarUnavailableSlotMarkerColor: '#DDDDDD',
      calendarServiceSlotBackgroundColor: '#8790FF30',
      calendarServiceSlotColor: '#FFFFFF',
      calendarServiceSlotMarkerColor: '#8790FF',
      subscriptionBorderColor: '#333333',
      subscriptionBackgroundColor: '#1A1A1A',
      selectedSubscriptionBorderColor: '#8790FF30',
      selectedSubscriptionBackgroundColor: '#8790FF',
    },
  },
};
