const primary100 = '#7B5AED';
const primary60 = '#7B5AED60';
const primary20 = '#7B5AED20';

export const lightTheme = {
  background: '#F2F2F2',
  background1: '#FFFFFF',
  color: '#000000',
  colorPress: '#000000',
  error: '#C62828',
  link: primary100,
  placeholderColor: '#999999',
  disabled: '#999999',
  highlighted: '#EEEEEE',
  borderColor: '#111111',
  borderColorHover: 'transparent',
  borderColorFocus: 'transparent',
  outlineColor: 'transparent',
  buttonBackground: primary100,
  buttonTextColor: '#FFFFFF',
  buttonTextColor1: primary100,
  checkboxColor: primary100,
  inputBackgroundColor: '#FFFFFF',
  tabBarActiveTintColor: primary100,
  tabBarInactiveTintColor: '#999999',
  qrCode: '#191919',
  qrCodeGradientFrom: primary100,
  qrCodeGradientTo: primary60,
  calendarBackgroundColor: '#FAFAFA',
  calendarLineColor: '#EFEFEF',
  calendarTimeColor: '#191919',
  calendarTodayColor: primary100,
  calendarNowIndicatorColor: primary100,
  switchSelectedColor: primary100
};

export const darkTheme = {
  background: '#000000',
  background1: '#191919',
  color: '#FFFFFF',
  colorPress: '#FFFFFF',
  error: '#FF6B6B',
  link: primary100,
  placeholderColor: '#999999',
  disabled: '#999999',
  highlighted: '#333333',
  borderColor: '#F5F5F5',
  borderColorHover: 'transparent',
  borderColorFocus: 'transparent',
  outlineColor: 'transparent',
  buttonBackground: primary100,
  buttonTextColor: '#FFFFFF',
  buttonTextColor1: primary100,
  checkboxColor: primary100,
  inputBackgroundColor: '#1A1A1A',
  tabBarActiveTintColor: primary100,
  tabBarInactiveTintColor: '#999999',
  qrCode: '#F5F5F5',
  qrCodeGradientFrom: primary100,
  qrCodeGradientTo: primary20,
  calendarBackgroundColor: '#0F0F0F',
  calendarLineColor: '#1A1A1A',
  calendarTimeColor: '#DDDDDD',
  calendarTodayColor: primary100,
  calendarNowIndicatorColor: primary100,
  switchSelectedColor: primary100
};
