import { AppSettings } from '@symbiot-core-apps/api';

const languages = {
  uk: require('./i18n/uk.json'),
  en: require('./i18n/en.json'),
};

export const appSettings: AppSettings = {
  language: {
    default: 'en',
    translations: languages,
  },
  functionality: {
    limits: {
      default: {
        clients: 100,
        services: 10,
        employees: 0,
        locations: 0,
        periodMemberships: 10,
        visitMemberships: 10,
      },
    },
    available: {
      leaveReview: true,
      reportIssue: true,
      partnerProgram: true,
      brandCompetitor: false,
      brandIndustry: false,
      servicePrice: false,
    },
  },
  icons: {
    Home: 'Home',
    Notifications: 'Bell',
    Calendar: 'Calendar',
    TabsPlus: 'AddCircle',
    Workspace: 'MagicStick',
    Service: 'Suitcase',
    Package: 'MusicLibrary2',
    More: 'Widget3',
    PeriodBasedMembership: 'TicketStar',
    VisitBasedMembership: 'Ticket',
    UnavailableBooking: 'CalendarCross',
    ServiceBooking: 'Calendar',
  },
  theme: {
    light: {
      background: '#F2F2F2',
      background1: '#FFFFFF',
      background2: '#FFFFFF50',
      overlay: '#11111180',
      color: '#000000',
      colorPress: '#000000',
      error: '#C62828',
      link: '#333333',
      placeholderColor: '#777777',
      disabled: '#999999',
      highlighted: '#EEEEEE',
      borderColor: '#111111',
      borderColorHover: 'transparent',
      borderColorFocus: 'transparent',
      outlineColor: 'transparent',
      buttonBackground: '#000000',
      buttonTextColor: '#FFFFFF',
      buttonTextColor1: '#000000',
      checkboxColor: '#111111',
      inputBackgroundColor: '#FFFFFF',
      tabBarActiveTintColor: '#000000',
      tabBarInactiveTintColor: '#999999',
      qrCode: '#191919',
      qrCodeGradientFrom: '#000000',
      qrCodeGradientTo: '#191919',
      calendarHeaderBackgroundColor: '#FAFAFA',
      switchSelectedColor: '#191919',
      calendarBackgroundColor: '#FFFFFF',
      calendarLineColor: '#EFEFEF',
      calendarTimeColor: '#191919',
      calendarTodayColor: '#000000',
      calendarNowIndicatorColor: '#000000',
      calendarUnavailableSlotBackgroundColor: '#EEEEEE',
      calendarUnavailableSlotColor: '#777777',
      calendarUnavailableSlotMarkerColor: '#DDDDDD',
      calendarServiceSlotBackgroundColor: '#8790FF30',
      calendarServiceSlotColor: '#000000',
      calendarServiceSlotMarkerColor: '#8790FF',
      subscriptionBorderColor: '#FEFEFE',
      subscriptionBackgroundColor: '#F2F2F2',
      selectedSubscriptionBorderColor: '#8790FF',
      selectedSubscriptionBackgroundColor: '#8790FF30',
    },
    dark: {
      background: '#000000',
      background1: '#191919',
      background2: '#19191950',
      overlay: '#11111180',
      color: '#FFFFFF',
      colorPress: '#FFFFFF',
      error: '#FF6B6B',
      link: '#EEEEEE',
      placeholderColor: '#999999',
      disabled: '#999999',
      highlighted: '#333333',
      borderColor: '#F5F5F5',
      borderColorHover: 'transparent',
      borderColorFocus: 'transparent',
      outlineColor: 'transparent',
      buttonBackground: '#FFFFFF',
      buttonTextColor: '#000000',
      buttonTextColor1: '#FFFFFF',
      checkboxColor: '#F5F5F5',
      inputBackgroundColor: '#1A1A1A',
      tabBarActiveTintColor: '#FFFFFF',
      tabBarInactiveTintColor: '#999999',
      qrCode: '#F5F5F5',
      qrCodeGradientFrom: '#F5F5F5',
      qrCodeGradientTo: '#FFFFFF',
      switchSelectedColor: '#DDDDDD',
      calendarHeaderBackgroundColor: '#0F0F0F',
      calendarBackgroundColor: '#000000',
      calendarLineColor: '#1A1A1A',
      calendarTimeColor: '#DDDDDD',
      calendarTodayColor: '#FFFFFF',
      calendarNowIndicatorColor: '#FFFFFF',
      calendarUnavailableSlotBackgroundColor: '#333333',
      calendarUnavailableSlotColor: '#777777',
      calendarUnavailableSlotMarkerColor: '#DDDDDD',
      calendarServiceSlotBackgroundColor: '#8790FF30',
      calendarServiceSlotColor: '#FFFFFF',
      calendarServiceSlotMarkerColor: '#8790FF',
      subscriptionBorderColor: '#1A1A1A',
      subscriptionBackgroundColor: '#333333',
      selectedSubscriptionBorderColor: '#8790FF',
      selectedSubscriptionBackgroundColor: '#8790FF30',
    },
  },
};
