export const getCountryEmoji = (code: string) => {
  return String.fromCodePoint(
    ...[...code.toUpperCase()].map(
      (char) => 0x1f1e6 + char.charCodeAt(0) - 'A'.charCodeAt(0),
    ),
  );
};

export const countryNameInNativeLanguage = {
  AD: 'Andorra',
  AE: 'الإمارات العربية المتحدة',
  AF: 'Afghanistan',
  AG: 'Antigua and Barbuda',
  AI: 'Anguilla',
  AL: 'Shqipëria',
  AM: 'Հայաստան',
  AO: 'Angola',
  AQ: 'Antarctica',
  AR: 'Argentina',
  AS: 'American Samoa',
  AT: 'Österreich',
  AU: 'Australia',
  AW: 'Aruba',
  AX: 'Åland',
  AZ: 'Azərbaycan',
  BA: 'Bosna i Hercegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'België',
  BF: 'Burkina Faso',
  BG: 'България',
  BH: 'البحرين',
  BI: 'Burundi',
  BJ: 'Bénin',
  BL: 'Saint-Barthélemy',
  BM: 'Bermuda',
  BN: 'Brunei Darussalam',
  BO: 'Bolivia (Plurinational State of)',
  BQ: 'Caribbean Netherlands',
  BR: 'Brasil',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BW: 'Botswana',
  BY: 'Беларусь',
  BZ: 'Belize',
  CA: 'Canada',
  CC: 'Cocos (Keeling) Islands',
  CD: 'République démocratique du Congo',
  CF: 'République centrafricaine',
  CG: 'République du Congo',
  CH: 'Schweiz',
  CI: "Côte d'Ivoire",
  CK: 'Cook Islands',
  CL: 'Chile',
  CM: 'Cameroun',
  CN: '中国',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cabo Verde',
  CW: 'Curaçao',
  CX: 'Christmas Island',
  CY: 'Κυπριακή Δημοκρατία',
  CZ: 'Česko',
  DE: 'Deutschland',
  DJ: 'Djibouti',
  DK: 'Danmark',
  DM: 'Dominica',
  DO: 'República Dominicana',
  DZ: 'الجزائر',
  EC: 'Ecuador',
  EE: 'Eesti',
  EG: 'مصر',
  EH: 'الصحراء الغربية',
  ER: 'ኤርትራ',
  ES: 'España',
  ET: 'ኢትዮጵያ',
  FI: 'Suomi',
  FJ: 'Fiji',
  FK: 'Falkland Islands',
  FM: 'Micronesia (Federated States of)',
  FO: 'Føroyar',
  FR: 'France',
  GA: 'Gabon',
  GB: 'United Kingdom',
  GD: 'Grenada',
  GE: 'საქართველო',
  GF: 'Guyane française',
  GG: 'Guernsey',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GL: 'Kalaallit Nunaat',
  GM: 'Gambia',
  GN: 'Guinée',
  GP: 'Guadeloupe',
  GQ: 'Guinea Ecuatorial',
  GR: 'Ελλάδα',
  GS: 'South Georgia and the South Sandwich Islands',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Guiné-Bissau',
  GY: 'Guyana',
  HK: '香港',
  HN: 'Honduras',
  HR: 'Hrvatska',
  HT: 'Haïti',
  HU: 'Magyarország',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'ישראל',
  IM: 'Isle of Man',
  IN: 'India',
  IO: 'British Indian Ocean Territory',
  IQ: 'العراق',
  IR: 'ایران',
  IS: 'Ísland',
  IT: 'Italia',
  JE: 'Jersey',
  JM: 'Jamaica',
  JO: 'الأردن',
  JP: '日本',
  KE: 'Kenya',
  KG: 'Кыргызстан',
  KH: 'កម្ពុជា',
  KI: 'Kiribati',
  KM: 'Comores',
  KN: 'Saint Kitts and Nevis',
  KP: '조선민주주의인민공화국',
  KR: '대한민국',
  KW: 'الكويت',
  KY: 'Cayman Islands',
  KZ: 'Қазақстан',
  LA: 'ລາວ',
  LB: 'لبنان',
  LC: 'Saint Lucia',
  LI: 'Liechtenstein',
  LK: 'ශ්‍රී ලංකා',
  LR: 'Liberia',
  LS: 'Lesotho',
  LT: 'Lietuva',
  LU: 'Luxembourg',
  LV: 'Latvija',
  LY: 'ليبيا',
  MA: 'المغرب',
  MC: 'Monaco',
  MD: 'Moldova',
  ME: 'Црна Гора',
  MF: 'Saint-Martin',
  MG: 'Madagasikara',
  MH: 'Marshall Islands',
  MK: 'Северна Македонија',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Монгол Улс',
  MO: '澳門',
  MP: 'Northern Mariana Islands',
  MQ: 'Martinique',
  MR: 'موريتانيا',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MW: 'Malawi',
  MX: 'México',
  MY: 'Malaysia',
  MZ: 'Moçambique',
  NA: 'Namibia',
  NC: 'Nouvelle-Calédonie',
  NE: 'Niger',
  NF: 'Norfolk Island',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Nederland',
  NO: 'Norge',
  NP: 'नेपाल',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'New Zealand',
  OM: 'عُمان',
  PA: 'Panamá',
  PE: 'Perú',
  PF: 'Polynésie française',
  PG: 'Papua New Guinea',
  PH: 'Pilipinas',
  PK: 'پاکستان',
  PL: 'Polska',
  PM: 'Saint-Pierre-et-Miquelon',
  PN: 'Pitcairn Islands',
  PR: 'Puerto Rico',
  PS: 'فلسطين',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'قطر',
  RE: 'Réunion',
  RO: 'România',
  RS: 'Србија',
  RU: 'Россия',
  RW: 'Rwanda',
  SA: 'المملكة العربية السعودية',
  SB: 'Solomon Islands',
  SC: 'Seychelles',
  SD: 'السودان',
  SE: 'Sverige',
  SG: 'Singapore',
  SH: 'Saint Helena, Ascension and Tristan da Cunha',
  SI: 'Slovenija',
  SJ: 'Svalbard og Jan Mayen',
  SK: 'Slovensko',
  SL: 'Sierra Leone',
  SM: 'San Marino',
  SN: 'Sénégal',
  SO: 'Soomaaliya',
  SR: 'Suriname',
  SS: 'South Sudan',
  ST: 'São Tomé and Príncipe',
  SV: 'El Salvador',
  SX: 'Sint Maarten',
  SY: 'سوريا',
  SZ: 'Eswatini',
  TC: 'Turks and Caicos Islands',
  TD: 'Tchad',
  TF: 'Terres australes françaises',
  TG: 'Togo',
  TH: 'ประเทศไทย',
  TJ: 'Тоҷикистон',
  TK: 'Tokelau',
  TL: 'Timor-Leste',
  TM: 'Türkmenistan',
  TN: 'تونس',
  TO: 'Tonga',
  TR: 'Türkiye',
  TT: 'Trinidad and Tobago',
  TV: 'Tuvalu',
  TW: '臺灣',
  TZ: 'Tanzania, United Republic of',
  UA: 'Україна',
  UG: 'Uganda',
  UM: 'United States Minor Outlying Islands',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Oʻzbekiston',
  VA: 'Holy See',
  VC: 'Saint Vincent and the Grenadines',
  VE: 'Venezuela (Bolivarian Republic of)',
  VG: 'British Virgin Islands',
  VI: 'United States Virgin Islands',
  VN: 'Việt Nam',
  VU: 'Vanuatu',
  WF: 'Wallis and Futuna',
  WS: 'Samoa',
  YE: 'اليمن',
  YT: 'Mayotte',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
};
